### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by myatix** [pnp/modernization#611]
#### Problem Area

[ x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

PnP Script "Convert-WikiAndWebPartPages.ps1" fails with latest version of PnP.Powershell.

ConvertTo-PnPClientSidePage needs updating to use the new ConvertTo-PnPPage.

**Comment by pkbullock** [comment]
Hi,
Thank you for the reporting this, 
We won't be upgrading these scripts in this repo because this relates to the version of the modernisation tooling used in the older classic PnP PowerShell module. 

However, we can look to upgrade these in future releases of the new modernisation tooling, so thanks for highlighting.

**Comment by myatix** [comment]
@pkbullock Thanks for the response! Can you provide a link to the new modernization tools/ scripts?

Thanks!

**Comment by jansenbe** [comment]
@myatix :  Did you manage to solve your issue by updating the existing scripts? If not then please create a new issue in the PnP Framework repo, will close this one.
